# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Component_Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Component_Test

  target 'Component_TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Component_TestUITests' do
    # Pods for testing
  end

end
